changelog:
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Maintenance
      labels:
        - chore
        - dependencies
        - refactor
    - title: Other Changes
      labels:
        - "*"
  exclude:
    labels:
      - no-changelog
    authors:
      - dependabot
      - dependabot[bot]
